#!/bin/bash
# deploy-dev.sh
set -euo pipefail

IMAGE_NAME=${IMAGE_NAME:-kyc-services:latest}
TAR_FILE=${TAR_FILE:-kyc-services-image.tar}
REMOTE_HOST=${REMOTE_HOST:-192.168.179.21}
REMOTE_USER=${REMOTE_USER:-devops}
REMOTE_DIR=${REMOTE_DIR:-/home/${REMOTE_USER}/projects}
REMOTE_DEBUG_PORT=${REMOTE_DEBUG_PORT:-5005}
REMOTE_DEBUG_SUSPEND=${REMOTE_DEBUG_SUSPEND:-n}
ENABLE_REMOTE_DEBUG=${ENABLE_REMOTE_DEBUG:-true}

docker save $IMAGE_NAME -o $TAR_FILE
ssh $REMOTE_USER@$REMOTE_HOST "mkdir -p ${REMOTE_DIR}"
scp $TAR_FILE $REMOTE_USER@$REMOTE_HOST:${REMOTE_DIR}/
ssh $REMOTE_USER@$REMOTE_HOST "docker load -i ${REMOTE_DIR}/$TAR_FILE && docker rm -f kyc-services || true && docker run -d --name kyc-services -p 8002:8002 -p 5432:5432 -p ${REMOTE_DEBUG_PORT}:${REMOTE_DEBUG_PORT} -e ENABLE_REMOTE_DEBUG=${ENABLE_REMOTE_DEBUG} -e REMOTE_DEBUG_PORT=${REMOTE_DEBUG_PORT} -e REMOTE_DEBUG_SUSPEND=${REMOTE_DEBUG_SUSPEND} $IMAGE_NAME"
